### ISSUE TITLE
Subscribing to events causes SSEClient errors

### ISSUE THREAD

**Issue by umamiking** [youngsoul/PyParticleIO#2]
Hi, I am trying to subscribe to a simple event (it doesn't matter if it's device specific or not), but I keep running into errors with SSEClient. The first is it complains that retry is not a valid parameter, so I removed it. Then it complained about url = url, which I also updated to be just `url`. But now it's complaining `TypeError: 'SSEClient' object is not iterable` and also `NameError: name 'time' is not defined`. Maybe this project was coded for a specific version of SSEClient and now it's outdated?

**Comment by youngsoul** [comment]
You might be right about the stale SSEClient version in the dependencies.  I just uploaded v0.1.0 with refreshed dependencies.  I also tested it locally and it worked for me.

Can you try the new pypi package:  0.1.0.

Thanks for point this out - and let me know how that works for you.
