### ISSUE TITLE
Printing the url will reveal the access token in output and eventually in my logfiles

### ISSUE THREAD

**Issue by unitware** [youngsoul/PyParticleIO#6]
I'd prefer that the sensitive access token was not printed for security reasons.

https://github.com/youngsoul/PyParticleIO/blob/3c95c932472ceaf3889405d8f9b16a93ec48ead7/pyparticleio/ParticleCloud.py#L260

https://github.com/youngsoul/PyParticleIO/blob/3c95c932472ceaf3889405d8f9b16a93ec48ead7/pyparticleio/ParticleCloud.py#L275

**Comment by youngsoul** [comment]
Good thought.  I am happy to take a PR.  Thanks for your input

**Comment by unitware** [comment]
https://github.com/youngsoul/PyParticleIO/pull/7
